function fillProductSelects(){const f=$('productForm');f.elements.category_id.innerHTML=snapshot.categories.map(c=>`<option value="${c.id}">${Z.esc(c.name)}</option>`).join('');f.elements.station_id.innerHTML=snapshot.stations.map(s=>`<option value="${s.id}">${Z.esc(s.name)}</option>`).join('');}
$('adminSearch').oninput=renderMenuAdmin;
function renderMenuAdmin(){if(!snapshot)return;const q=$('adminSearch').value.trim().toLowerCase(),items=snapshot.items.filter(i=>!q||i.name.toLowerCase().includes(q));$('adminItems').innerHTML=items.map(i=>`<article class="admin-item"><div><h5>${Z.esc(i.name)}</h5><p>${Z.esc(i.description||'')} · ${i.active?'активен':'скрит'}</p></div><div><input class="quick-price" type="number" step="0.01" value="${Number(i.price||0)}" data-price="${i.id}"><button class="btn" style="min-height:34px" data-edit="${i.id}">Редакция</button></div></article>`).join('');$('adminItems').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editProduct(b.dataset.edit));$('adminItems').querySelectorAll('[data-price]').forEach(i=>i.oninput=()=>dirtyPrices.set(i.dataset.price,Number(i.value)));}
function resetProductForm(){$('productForm').reset();$('productForm').elements.id.value='';$('productForm').elements.price.value=0;$('productForm').elements.price_pending.checked=true;$('productForm').elements.send_to_kitchen.checked=true;$('productForm').elements.available_for_pickup.checked=true;$('productForm').elements.active.checked=true;$('editorTitle').textContent='Нов продукт';editingProduct=null;fillProductSelects();}
$('newProduct').onclick=resetProductForm;
function editProduct(id){const i=snapshot.items.find(x=>x.id===id);editingProduct=i;const f=$('productForm').elements;f.id.value=i.id;f.name.value=i.name;f.category_id.value=i.category_id||'';f.station_id.value=i.station_id||'';f.price.value=i.price||0;f.quantity_mode.value=i.quantity_mode;f.default_piece_count.value=i.default_piece_count||'';f.sort_order.value=i.sort_order||0;f.description.value=i.description||'';f.image_url.value=i.image_url||'';f.price_pending.checked=i.price_pending;f.includes_fries.checked=i.includes_fries;f.send_to_kitchen.checked=i.send_to_kitchen;f.available_for_pickup.checked=i.available_for_pickup;f.active.checked=i.active;$('editorTitle').textContent=`Редакция · ${i.name}`;window.scrollTo({top:0,behavior:'smooth'});}
async function fileToDataUrl(file){if(!file)return null;if(file.size>1500000)throw new Error('Снимката трябва да е под 1.5 MB.');return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});}
$('productForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget.elements;try{const image=await fileToDataUrl(f.image_file.files[0]);const item={id:f.id.value||null,name:f.name.value,category_id:f.category_id.value,station_id:f.station_id.value,price:Number(f.price.value||0),quantity_mode:f.quantity_mode.value,default_piece_count:f.default_piece_count.value||null,sort_order:Number(f.sort_order.value||0),description:f.description.value,image_url:image||f.image_url.value||null,price_pending:f.price_pending.checked,includes_fries:f.includes_fries.checked,send_to_kitchen:f.send_to_kitchen.checked,available_for_pickup:f.available_for_pickup.checked,active:f.active.checked,option_schema:editingProduct?.option_schema||{}};await Z.rpc('zorbas_save_menu_item_v3',{p_token:Z.token(),p_item:item});Z.toast('Продуктът е запазен.','success');resetProductForm();refresh();}catch(error){Z.toast(error.message,'error');}};
$('deleteProduct').onclick=async()=>{const id=$('productForm').elements.id.value;if(!id)return;if(!confirm('Да се изтрие ли продуктът?'))return;try{await Z.rpc('zorbas_delete_menu_item_v3',{p_token:Z.token(),p_item_id:id});Z.toast('Продуктът е изтрит.','success');resetProductForm();refresh();}catch(error){Z.toast(error.message,'error');}};
$('saveAllPrices').onclick=async()=>{if(!dirtyPrices.size)return Z.toast('Няма променени цени.');try{for(const [id,price] of dirtyPrices){const i=snapshot.items.find(x=>x.id===id);await Z.rpc('zorbas_save_menu_item_v3',{p_token:Z.token(),p_item:{...i,description:i.description,price,price_pending:false,station_id:i.station_id}});}dirtyPrices.clear();Z.toast('Всички цени са запазени.','success');refresh();}catch(error){Z.toast(error.message,'error');}};

$('adminUnlockForm').onsubmit=async e=>{e.preventDefault();const pin=new FormData(e.currentTarget).get('pin');try{await Z.rpc('zorbas_admin_unlock',{p_token:Z.token(),p_pin:pin});$('adminLock').classList.add('hidden');$('statsContent').classList.remove('hidden');loadStats('day');}catch(error){Z.toast(error.message,'error');}};
document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-range]').forEach(x=>x.classList.toggle('active',x===b));loadStats(b.dataset.range);});
function rangeDates(range){const to=new Date(),from=new Date(to);if(range==='day')from.setHours(0,0,0,0);if(range==='week')from.setDate(from.getDate()-7);if(range==='month')from.setMonth(from.getMonth()-1);if(range==='year')from.setFullYear(from.getFullYear()-1);if(range==='10years')from.setFullYear(from.getFullYear()-10);return {from,to};}
async function loadStats(range){const r=rangeDates(range);try{const d=await Z.rpc('zorbas_admin_stats_v3',{p_token:Z.token(),p_from:r.from.toISOString(),p_to:r.to.toISOString()});$('statsCards').innerHTML=[['Заведение',d.restaurant_total],['Сайт',d.website_total],['Общо',d.grand_total],['Отказани',d.cancelled_total],['Върнати',d.returned_total]].map(([l,v])=>`<article class="stat"><small>${l}</small><strong>${Z.money(v)}</strong></article>`).join('');$('statsDays').innerHTML=(d.by_day||[]).map(x=>`<tr><td>${Z.esc(x.day_key)}</td><td>${x.orders}</td><td>${Z.money(x.total)}</td></tr>`).join('');$('statsItems').innerHTML=(d.top_items||[]).map(x=>`<tr><td>${Z.esc(x.item_name)}</td><td>${x.quantity}</td><td>${Z.money(x.total)}</td></tr>`).join('');}catch(error){Z.toast(error.message,'error');}}

updateOrderType();init();