(() => {
  if (window.ZorbasManagerModule) return;
  window.ZorbasManagerModule = true;

  const state = {
    notesQuery: '', managerQuery: '', archiveQuery: '', archiveRange: 'today',
    archiveRows: [], archiveLoading: false, editOrderId: null, actionBusy: new Set()
  };
  const stateLabels = {new:'НОВО',assigned:'ВЪЗЛОЖЕНО',sent:'ИЗПРАТЕНО',delivered:'ДАДЕНО',cancelled:'ОТКАЗАНО'};
  const escape = value => Z.esc(value == null ? '' : String(value));
  const normalize = value => String(value || '').trim().toLowerCase();
  const tableFor = id => snapshot?.tables?.find(table => table.id === id) || null;
  const visitFor = id => snapshot?.visits?.find(visit => visit.id === id) || null;
  const orderFor = id => snapshot?.orders?.find(order => order.id === id) || null;
  const activeManagerOrders = () => (snapshot?.orders || []).filter(order => order.manager_state !== 'completed' && !['completed','cancelled','returned'].includes(order.status));

  function orderSearchText(order) {
    const table = tableFor(order.table_id), visit = visitFor(order.visit_id);
    return normalize([table?.table_number,order.order_number,order.created_by_name,visit?.guest_label,order.note,...(order.items||[]).flatMap(item=>[item.item_name,item.assigned_to,item.manager_note])].join(' '));
  }
  function orderTitle(order) {
    if (order.order_type === 'pickup') return 'ПАКЕТ / ЗА ВКЪЩИ';
    const table=tableFor(order.table_id), visit=visitFor(order.visit_id);
    return `МАСА ${escape(table?.table_number||'—')}${visit?.guest_label?` · ${escape(visit.guest_label)}`:''}`;
  }
  function ageMinutes(value){return Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/60000));}
  function revisionSummary(order){const revisions=order.revisions||[];if(!revisions.length)return'';const latest=revisions[0];const changes=(latest.delta_items||[]).map(change=>{const delta=Number(change.delta||0);return `${delta>0?'+':''}${delta} ${escape(change.name)}`;}).join(' · ');return `<p class="revision-note">Последна промяна: ${changes||'редакция'}${latest.actor_name?` · ${escape(latest.actor_name)}`:''}</p>`;}

  function renderNotes(){
    const root=document.getElementById('ordersList');if(!root||!snapshot)return;
    const query=normalize(document.getElementById('notesSearch')?.value||state.notesQuery);state.notesQuery=query;
    const orders=activeManagerOrders().filter(order=>!query||orderSearchText(order).includes(query));
    root.innerHTML=orders.length?orders.map(order=>{const active=(order.items||[]).filter(i=>i.status!=='cancelled'),cancelled=(order.items||[]).filter(i=>i.status==='cancelled');return `<article class="order-card note-card"><header class="card-head"><div><strong>${orderTitle(order)}</strong><br><small>Бележка №${order.order_number} · ${escape(order.created_by_name||'')} · версия ${Number(order.revision||1)}</small></div><span class="badge">${ageMinutes(order.created_at)} мин.</span></header><div class="card-body"><ul class="note-items">${active.map(item=>`<li><b>${Number(item.quantity)}×</b> ${escape(item.item_name)}${item.note?` — ${escape(item.note)}`:''}</li>`).join('')}</ul>${cancelled.length?`<div class="cancelled-lines"><small>ПРОМЕНЕНО / ОТКАЗАНО</small>${cancelled.map(item=>`<p>− ${Number(item.quantity)}× ${escape(item.item_name)}</p>`).join('')}</div>`:''}<p><b>${Z.money(order.subtotal)}</b>${order.note?` · ${escape(order.note)}`:''}</p>${revisionSummary(order)}</div><footer class="card-actions"><button class="btn primary" data-edit-note="${order.id}">РЕДАКТИРАЙ</button><button class="btn light" data-bill="${order.id}">СМЕТКА · PRINT 1</button><button class="btn" data-open-manager="${order.visit_id||order.id}">MANAGER</button></footer></article>`;}).join(''):'<p class="empty">Няма активни бележки по това търсене.</p>';
    root.querySelectorAll('[data-edit-note]').forEach(button=>button.onclick=()=>openEditOrder(button.dataset.editNote));
    root.querySelectorAll('[data-bill]').forEach(button=>button.onclick=async()=>{try{await Z.rpc('zorbas_print_bill_v3',{p_token:Z.token(),p_order_id:button.dataset.bill});Z.toast('Сметката е изпратена към Print 1.','success');}catch(error){Z.toast(error.message,'error');}});
    root.querySelectorAll('[data-open-manager]').forEach(button=>button.onclick=()=>{switchView('manager');const order=orders.find(entry=>(entry.visit_id||entry.id)===button.dataset.openManager),table=tableFor(order?.table_id),input=document.getElementById('managerSearch');if(input&&table)input.value=table.table_number;renderManager();});
  }

  function ensureEditDialog(){let dialog=document.getElementById('editOrderDialog');if(dialog)return dialog;dialog=document.createElement('dialog');dialog.id='editOrderDialog';dialog.className='manager-dialog';dialog.innerHTML=`<form method="dialog" class="manager-dialog-card" id="editOrderForm"><header><div><small>КОРЕКЦИЯ НА БЕЛЕЖКА</small><h3 id="editOrderTitle">Бележка</h3></div><button class="dialog-close" value="cancel">×</button></header><div id="editOrderRows" class="edit-order-rows"></div><label class="field">Причина / бележка<input id="editOrderReason" placeholder="Грешка, върнат продукт, клиентът отказа…"></label><section class="change-preview" id="editOrderPreview"><small>Промените ще се покажат тук.</small></section><footer><button class="btn" value="cancel">ОТКАЗ</button><button class="btn primary" id="saveOrderChanges" type="button">ЗАПАЗИ ПРОМЕНИТЕ</button></footer></form>`;document.body.appendChild(dialog);document.getElementById('saveOrderChanges').onclick=saveOrderChanges;return dialog;}
  function openEditOrder(orderId){const order=orderFor(orderId);if(!order)return;state.editOrderId=orderId;const dialog=ensureEditDialog();document.getElementById('editOrderTitle').textContent=`Бележка №${order.order_number}`;document.getElementById('editOrderReason').value='';document.getElementById('editOrderRows').innerHTML=(order.items||[]).map(item=>{const quantity=item.status==='cancelled'?0:Number(item.quantity);return `<div class="edit-order-row" data-edit-row="${item.id}" data-old="${quantity}" data-name="${escape(item.item_name)}"><div><b>${escape(item.item_name)}</b>${item.note?`<small>${escape(item.note)}</small>`:''}</div><div class="qty editor-qty"><button type="button" data-edit-minus="${item.id}">−</button><input inputmode="decimal" type="number" min="0" step="1" value="${quantity}" data-edit-quantity="${item.id}"><button type="button" data-edit-plus="${item.id}">+</button></div></div>`;}).join('');dialog.querySelectorAll('[data-edit-minus]').forEach(button=>button.onclick=()=>changeEditQuantity(button.dataset.editMinus,-1));dialog.querySelectorAll('[data-edit-plus]').forEach(button=>button.onclick=()=>changeEditQuantity(button.dataset.editPlus,1));dialog.querySelectorAll('[data-edit-quantity]').forEach(input=>input.oninput=updateEditPreview);updateEditPreview();dialog.showModal();}
  function changeEditQuantity(id,change){const input=document.querySelector(`[data-edit-quantity="${CSS.escape(id)}"]`);if(!input)return;input.value=Math.max(0,Number(input.value||0)+change);updateEditPreview();}
  function editPayload(){return [...document.querySelectorAll('[data-edit-row]')].map(row=>({id:row.dataset.editRow,name:row.dataset.name,oldQuantity:Number(row.dataset.old||0),quantity:Math.max(0,Number(row.querySelector('[data-edit-quantity]')?.value||0))}));}
  function updateEditPreview(){const changes=editPayload().filter(row=>row.quantity!==row.oldQuantity),preview=document.getElementById('editOrderPreview');if(!preview)return;if(!changes.length){preview.innerHTML='<small>Няма промени.</small>';return;}preview.innerHTML=`<b>ПРОМЕНЕНО</b>${changes.map(row=>{const delta=row.quantity-row.oldQuantity;return `<p class="${delta<0?'minus':'plus'}">${delta>0?'+':''}${delta} × ${escape(row.name)}</p>`;}).join('')}<hr><b>НОВО</b>${editPayload().filter(row=>row.quantity>0).map(row=>`<p>${row.quantity} × ${escape(row.name)}</p>`).join('')}`;}
  async function saveOrderChanges(){const order=orderFor(state.editOrderId);if(!order)return;const button=document.getElementById('saveOrderChanges'),rows=editPayload();if(!rows.some(row=>row.quantity!==row.oldQuantity))return Z.toast('Няма промени за запис.','error');button.disabled=true;button.textContent='ЗАПИСВА…';try{const result=await Z.rpc('zorbas_edit_order_v1',{p_token:Z.token(),p_order_id:order.id,p_expected_revision:Number(order.revision||1),p_items:rows.map(row=>({id:row.id,quantity:row.quantity})),p_reason:document.getElementById('editOrderReason').value||null});ensureEditDialog().close();Z.toast(`Бележката е променена. Версия ${result.revision}.`,'success');await refresh();}catch(error){Z.toast(error.message,'error');}finally{button.disabled=false;button.textContent='ЗАПАЗИ ПРОМЕНИТЕ';}}

  function managerItemRow(item){const stateName=item.status==='cancelled'?'cancelled':(item.manager_state||'new'),assigned=item.assigned_to||'',delivered=stateName==='delivered';return `<div class="manager-item state-${stateName} ${delivered?'is-delivered':''}"><div class="manager-item-main"><span class="manager-item-qty">${Number(item.quantity)}×</span><div><b>${escape(item.item_name)}</b>${item.note?`<small>${escape(item.note)}</small>`:''}${item.manager_note?`<small>↳ ${escape(item.manager_note)}</small>`:''}</div><span class="manager-state">${stateLabels[stateName]||escape(stateName)}</span></div>${stateName!=='cancelled'?`<div class="manager-item-actions"><input list="managerStaffList" class="small-input manager-assignee" value="${escape(assigned)}" placeholder="Кой?" data-assignee="${item.id}"><button class="btn mini" data-manager-action="assign" data-item="${item.id}" data-version="${Number(item.manager_version||1)}">ВЪЗЛОЖИ</button><button class="btn mini yellow" data-manager-action="sent" data-item="${item.id}" data-version="${Number(item.manager_version||1)}">ИЗПРАТЕНО</button><button class="btn mini green" data-manager-action="delivered" data-item="${item.id}" data-version="${Number(item.manager_version||1)}">✓ ДАДЕНО</button><button class="btn mini" data-manager-action="reset" data-item="${item.id}" data-version="${Number(item.manager_version||1)}">↶</button></div>`:''}</div>`;}
  function visitCard(visit){const table=tableFor(visit.table_id),orders=(snapshot.orders||[]).filter(order=>order.visit_id===visit.id),active=orders.filter(order=>order.manager_state!=='completed'&&!['cancelled','returned'].includes(order.status)),completed=orders.filter(order=>order.manager_state==='completed'),allItems=active.flatMap(order=>order.items||[]).filter(item=>item.status!=='cancelled'),newCount=allItems.filter(item=>(item.manager_state||'new')==='new').length,delivered=allItems.filter(item=>item.manager_state==='delivered').length,ready=active.length===0;return `<article class="manager-visit-card ${newCount?'has-new':''}"><header><div><small>${escape(visit.guest_label)}</small><strong>МАСА ${escape(table?.table_number||'—')}</strong><span>От ${Z.formatDate(visit.opened_at)}</span></div><div class="visit-counters"><b>${newCount} нови</b><span>${delivered}/${allItems.length} дадени</span></div></header><div class="manager-orders">${active.length?active.map(order=>`<section class="manager-order"><div class="manager-order-head"><b>Бележка №${order.order_number}</b><span>${escape(order.created_by_name||'')} · ${ageMinutes(order.created_at)} мин.</span></div>${(order.items||[]).map(managerItemRow).join('')}<footer><button class="btn green full" data-complete-order="${order.id}" ${(order.items||[]).some(item=>item.status!=='cancelled'&&item.manager_state!=='delivered')?'disabled':''}>ГОТОВО · В АРХИВ</button></footer></section>`).join(''):'<p class="visit-ready">Всички бележки на тези гости са приключени.</p>'}</div>${completed.length?`<details><summary>Приключени бележки (${completed.length})</summary>${completed.map(order=>`<p>✓ №${order.order_number} · ${Z.money(order.subtotal)}</p>`).join('')}</details>`:''}<footer class="visit-actions"><button class="btn primary" data-next-guests="${visit.table_id}" ${ready?'':'disabled'}>СЛЕДВАЩИ ГОСТИ</button><button class="btn" data-close-visit="${visit.table_id}" ${ready?'':'disabled'}>ОСВОБОДИ МАСАТА</button></footer></article>`;}
  function renderPeopleTasks(orders){const root=document.getElementById('managerPeople');if(!root)return;const grouped=new Map();orders.forEach(order=>(order.items||[]).forEach(item=>{if(!item.assigned_to||item.status==='cancelled'||item.manager_state==='delivered')return;const list=grouped.get(item.assigned_to)||[];list.push({item,order,table:tableFor(order.table_id)});grouped.set(item.assigned_to,list);}));root.innerHTML=grouped.size?[...grouped.entries()].map(([person,tasks])=>`<article class="person-card"><header><strong>${escape(person)}</strong><span>${tasks.length} задачи</span></header>${tasks.map(task=>`<p><b>Маса ${escape(task.table?.table_number||'—')}</b> · ${Number(task.item.quantity)}× ${escape(task.item.item_name)} <small>${stateLabels[task.item.manager_state]||task.item.manager_state}</small></p>`).join('')}</article>`).join(''):'<p class="empty">Няма възложени незавършени задачи.</p>';}
  function populateStaffList(){const list=document.getElementById('managerStaffList');if(list)list.innerHTML=(snapshot?.staff||[]).map(person=>`<option value="${escape(person.name)}"></option>`).join('');}
  function renderManager(){if(!snapshot)return;const root=document.getElementById('managerBoard');if(!root)return;populateStaffList();const query=normalize(document.getElementById('managerSearch')?.value||state.managerQuery);state.managerQuery=query;const activeVisits=(snapshot.visits||[]).filter(visit=>visit.status==='active'),activeOrders=activeManagerOrders();renderPeopleTasks(activeOrders);const visits=activeVisits.filter(visit=>{if(!query)return true;const table=tableFor(visit.table_id),orders=(snapshot.orders||[]).filter(order=>order.visit_id===visit.id);return normalize(`${table?.table_number||''} ${visit.guest_label||''} ${orders.map(orderSearchText).join(' ')}`).includes(query);}).sort((a,b)=>{const aNew=activeOrders.some(order=>order.visit_id===a.id&&(order.items||[]).some(item=>item.manager_state==='new')),bNew=activeOrders.some(order=>order.visit_id===b.id&&(order.items||[]).some(item=>item.manager_state==='new'));return Number(bNew)-Number(aNew)||new Date(a.opened_at)-new Date(b.opened_at);});const pickup=activeOrders.filter(order=>!order.visit_id&&(!query||orderSearchText(order).includes(query)));const firstNotNew=visits.findIndex(visit=>!activeOrders.some(order=>order.visit_id===visit.id&&(order.items||[]).some(item=>item.manager_state==='new')));const hasNew=visits.some(v=>activeOrders.some(o=>o.visit_id===v.id&&(o.items||[]).some(i=>i.manager_state==='new')));const cards=visits.map((visit,index)=>`${index===0&&hasNew?'<div class="manager-divider"><span>НОВО</span></div>':''}${index===firstNotNew&&firstNotNew>0?'<div class="manager-divider normal"><span>АКТИВНИ</span></div>':''}${visitCard(visit)}`).join('');root.innerHTML=cards+(pickup.length?`<div class="manager-divider normal"><span>ПАКЕТИ</span></div>${pickup.map(order=>`<article class="manager-visit-card"><header><div><small>ЗА ВКЪЩИ</small><strong>ПОРЪЧКА №${order.order_number}</strong></div></header><section class="manager-order">${(order.items||[]).map(managerItemRow).join('')}<footer><button class="btn green full" data-complete-order="${order.id}" ${(order.items||[]).some(item=>item.status!=='cancelled'&&item.manager_state!=='delivered')?'disabled':''}>ГОТОВО · В АРХИВ</button></footer></section></article>`).join('')}`:'')||'<p class="empty">Няма активни посещения или поръчки.</p>';root.querySelectorAll('[data-manager-action]').forEach(button=>button.onclick=()=>updateManagerItem(button));root.querySelectorAll('[data-complete-order]').forEach(button=>button.onclick=()=>completeOrder(button.dataset.completeOrder,button));root.querySelectorAll('[data-next-guests]').forEach(button=>button.onclick=()=>nextGuests(button.dataset.nextGuests,button));root.querySelectorAll('[data-close-visit]').forEach(button=>button.onclick=()=>closeVisit(button.dataset.closeVisit,button));}
  async function updateManagerItem(button){const itemId=button.dataset.item;if(state.actionBusy.has(itemId))return;const action=button.dataset.managerAction,input=document.querySelector(`[data-assignee="${CSS.escape(itemId)}"]`),assignedTo=input?.value?.trim()||null;if(action==='assign'&&!assignedTo)return Z.toast('Напиши или избери човек.','error');state.actionBusy.add(itemId);button.disabled=true;try{await Z.rpc('zorbas_manager_update_item_v1',{p_token:Z.token(),p_item_id:itemId,p_action:action,p_assigned_to:assignedTo,p_note:null,p_expected_version:Number(button.dataset.version||1)});await refresh();}catch(error){Z.toast(error.message,'error');}finally{state.actionBusy.delete(itemId);button.disabled=false;}}
  async function completeOrder(id,button){button.disabled=true;try{await Z.rpc('zorbas_manager_complete_order_v1',{p_token:Z.token(),p_order_id:id});Z.toast('Бележката е приключена и е в архива.','success');await refresh();}catch(error){Z.toast(error.message,'error');button.disabled=false;}}
  async function nextGuests(tableId,button){if(!confirm('Да архивирам ли сегашното посещение и да започна следващи гости на тази маса?'))return;button.disabled=true;try{const result=await Z.rpc('zorbas_start_next_guests_v1',{p_token:Z.token(),p_table_id:tableId});Z.toast(`${result.guest_label} са започнати.`,'success');await refresh();}catch(error){Z.toast(error.message,'error');button.disabled=false;}}
  async function closeVisit(tableId,button){if(!confirm('Да приключа посещението и да освободя масата?'))return;button.disabled=true;try{await Z.rpc('zorbas_close_visit_v1',{p_token:Z.token(),p_table_id:tableId});Z.toast('Посещението е архивирано и масата е свободна.','success');await refresh();}catch(error){Z.toast(error.message,'error');button.disabled=false;}}

  function archiveDates(range){const now=new Date(),to=new Date(now),from=new Date(now);if(range==='today')from.setHours(0,0,0,0);else if(range==='yesterday'){from.setDate(from.getDate()-1);from.setHours(0,0,0,0);to.setHours(0,0,0,0);}else if(range==='week')from.setDate(from.getDate()-7);else if(range==='month')from.setMonth(from.getMonth()-1);else if(range==='year')from.setFullYear(from.getFullYear()-1);else from.setFullYear(from.getFullYear()-20);return{from,to};}
  async function loadArchive(){if(state.archiveLoading||!Z.token())return;state.archiveLoading=true;const root=document.getElementById('archiveList');if(root)root.innerHTML='<p class="empty">Зареждане на архива…</p>';try{const dates=archiveDates(state.archiveRange);state.archiveRows=await Z.rpc('zorbas_manager_archive_v1',{p_token:Z.token(),p_from:dates.from.toISOString(),p_to:dates.to.toISOString(),p_query:document.getElementById('archiveSearch')?.value||null});renderArchive();}catch(error){if(root)root.innerHTML=`<p class="empty">${escape(error.message)}</p>`;}finally{state.archiveLoading=false;}}
  function renderArchive(){const root=document.getElementById('archiveList');if(!root)return;root.innerHTML=state.archiveRows.length?state.archiveRows.map(order=>`<article class="archive-card"><header><div><strong>${order.order_type==='pickup'?'ПАКЕТ':`МАСА ${escape(order.table_number||'—')}`} ${order.guest_label?`· ${escape(order.guest_label)}`:''}</strong><small>№${order.order_number} · ${Z.formatDate(order.created_at)}</small></div><b>${Z.money(order.subtotal)}</b></header><div>${(order.items||[]).map(item=>`<p class="${item.status==='cancelled'?'archive-cancelled':''}">${item.status==='cancelled'?'−':'✓'} ${Number(item.quantity)}× ${escape(item.item_name)}${item.assigned_to?` · ${escape(item.assigned_to)}`:''}</p>`).join('')}</div><footer><span>Сервитьор: ${escape(order.created_by_name||'—')}</span><span>Приключил: ${escape(order.completed_by_name||'—')}</span><span>Редакции: ${Math.max(0,Number(order.revision||1)-1)}</span></footer></article>`).join(''):'<p class="empty">Няма архивирани бележки за периода.</p>';}
  function dashboardDates(range){const now=new Date(),to=new Date(now),from=new Date(now);if(range==='today'||range==='day')from.setHours(0,0,0,0);else if(range==='yesterday'){from.setDate(from.getDate()-1);from.setHours(0,0,0,0);to.setHours(0,0,0,0);}else if(range==='week')from.setDate(from.getDate()-7);else if(range==='month')from.setMonth(from.getMonth()-1);else if(range==='year')from.setFullYear(from.getFullYear()-1);else from.setFullYear(from.getFullYear()-20);return{from,to};}
  async function loadDashboard(range){const dates=dashboardDates(range);try{const data=await Z.rpc('zorbas_admin_dashboard_v1',{p_token:Z.token(),p_from:dates.from.toISOString(),p_to:dates.to.toISOString()});const cards=[['Поръчки',data.orders_count],['Посещения',data.visits_count],['Приключени бележки',data.completed_orders],['Обща стойност',Z.money(data.gross_total)],['Чиста стойност',Z.money(data.net_total)],['Средна сметка',Z.money(data.average_bill)],['Корекции',data.corrections_count],['На място',data.dine_in_count],['За вкъщи',data.pickup_count]];document.getElementById('statsCards').innerHTML=cards.map(([label,value])=>`<article class="stat"><small>${label}</small><strong>${value}</strong></article>`).join('');document.getElementById('statsDays').innerHTML=(data.tables||[]).map(row=>`<tr><td>Маса ${escape(row.table_number)}</td><td>${row.visits}</td><td>${row.occupied_minutes} мин.</td><td>${Z.money(row.total)}</td></tr>`).join('');document.getElementById('statsItems').innerHTML=(data.top_items||[]).map(row=>`<tr><td>${escape(row.item_name)}</td><td>${row.quantity}</td><td>${Z.money(row.total)}</td></tr>`).join('');const hours=document.getElementById('statsHours');if(hours)hours.innerHTML=(data.by_hour||[]).map(row=>`<tr><td>${String(row.hour_key).padStart(2,'0')}:00</td><td>${row.orders}</td><td>${Z.money(row.total)}</td></tr>`).join('');}catch(error){Z.toast(error.message,'error');}}

  function enhanceTableInfo(){const root=document.getElementById('tableInfo'),table=tableFor(selectedTable);if(!root||!table||root.querySelector('[data-visit-quick-actions]'))return;const visit=visitFor(table.active_visit_id);if(!visit)return;const activeOrders=(snapshot.orders||[]).filter(order=>order.visit_id===visit.id&&order.manager_state!=='completed');const actions=document.createElement('div');actions.className='visit-quick-actions';actions.dataset.visitQuickActions='1';actions.innerHTML=`<p><b>${escape(visit.guest_label)}</b> · започнати ${Z.formatDate(visit.opened_at)}</p><div class="toolbar"><button class="btn primary" data-quick-next ${activeOrders.length?'disabled':''}>СЛЕДВАЩИ ГОСТИ</button><button class="btn" data-quick-close ${activeOrders.length?'disabled':''}>ОСВОБОДИ</button></div>`;root.appendChild(actions);actions.querySelector('[data-quick-next]').onclick=event=>nextGuests(table.id,event.currentTarget);actions.querySelector('[data-quick-close]').onclick=event=>closeVisit(table.id,event.currentTarget);}
  const baseRenderTableInfo=typeof renderTableInfo==='function'?renderTableInfo:null;if(baseRenderTableInfo)renderTableInfo=function(){baseRenderTableInfo();enhanceTableInfo();};
  const baseRenderAll=typeof renderAll==='function'?renderAll:null;if(baseRenderAll)renderAll=function(){baseRenderAll();renderNotes();renderManager();if(activeView==='archive')loadArchive();if(selectedTable)enhanceTableInfo();};
  renderOrders=renderNotes;
  const baseSwitchView=typeof switchView==='function'?switchView:null;if(baseSwitchView)switchView=function(name){baseSwitchView(name);if(name==='manager')renderManager();if(name==='archive')loadArchive();};

  const notesSearch=document.getElementById('notesSearch');if(notesSearch)notesSearch.oninput=renderNotes;
  const managerSearch=document.getElementById('managerSearch');if(managerSearch)managerSearch.oninput=renderManager;
  const archiveRefresh=document.getElementById('archiveRefresh');if(archiveRefresh)archiveRefresh.onclick=loadArchive;
  const archiveSearch=document.getElementById('archiveSearch');if(archiveSearch){let timer;archiveSearch.oninput=()=>{clearTimeout(timer);timer=setTimeout(loadArchive,300);};}
  document.querySelectorAll('[data-archive-range]').forEach(button=>button.onclick=()=>{state.archiveRange=button.dataset.archiveRange;document.querySelectorAll('[data-archive-range]').forEach(entry=>entry.classList.toggle('active',entry===button));loadArchive();});
  document.querySelectorAll('[data-dashboard-range]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-dashboard-range]').forEach(entry=>entry.classList.toggle('active',entry===button));loadDashboard(button.dataset.dashboardRange);});
  if(typeof loadStats==='function')loadStats=loadDashboard;
  if(snapshot){renderNotes();renderManager();}
})();
