(() => {
  const Z = window.Zorbas, $ = id => document.getElementById(id);
  let destination = 'staff', jobs = [], timer = null;

  async function login(event) {
    event.preventDefault(); const f = new FormData(event.currentTarget); $('loginMessage').textContent = 'Влизане…';
    try { const d = await Z.rpc('zorbas_staff_login',{p_username:f.get('username'),p_password:f.get('password'),p_display_name:f.get('display_name'),p_device_id:Z.deviceId()}); Z.setToken(d.token); await start(); }
    catch(e){ $('loginMessage').textContent=e.message; }
  }
  async function start(){ const s=await Z.requireSession(); if(!s)return; $('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('sessionName').textContent=`${s.display_name} · печатна опашка`;await refresh();timer=setInterval(refresh,5000); }
  async function refresh(){ try{jobs=await Z.rpc('zorbas_list_print_jobs_v3',{p_token:Z.token(),p_destination:destination});render();}catch(e){Z.toast(e.message,'error')} }
  function title(type){return type==='cancellation'?'ОТКАЗАНА ПОРЪЧКА':type==='bill'?'СМЕТКА':type==='pickup'?'ПАКЕТ · ЗА ВКЪЩИ':type==='addition'?'ДОБАВКА':'ПОРЪЧКА'}
  function render(){ $('jobsList').innerHTML=jobs.length?jobs.map(j=>{const p=j.payload||{};return `<article class="order-card"><header><div><strong>${title(j.job_type)}</strong><small>${destination==='staff'?'Print 1 · сервитьори':'Print 2 · кухня'} · ${Z.formatDate(j.created_at)}</small></div><span class="badge ${j.status==='failed'?'cancelled':''}">${j.status}</span></header><div class="panel-body"><p><b>${p.order_type==='pickup'?'ПАКЕТ':`МАСА ${Z.esc(p.table_number||'—')}`}</b> · №${Z.esc(p.order_number||'—')}</p><p>${(p.items||[]).map(i=>`${i.quantity}× ${Z.esc(i.name)}`).join('<br>')}</p>${p.cancel_reason?`<p class="notice">ОТКАЗ: ${Z.esc(p.cancel_reason)}</p>`:''}${p.note||p.order_note?`<p class="notice">${Z.esc(p.note||p.order_note)}</p>`:''}<div class="toolbar"><button class="btn primary" data-print="${j.id}">ПЕЧАТ</button><button class="btn red" data-fail="${j.id}">ОТБЕЛЕЖИ ГРЕШКА</button></div></div></article>`}).join(''):'<div class="empty">Няма чакащи бележки.</div>';document.querySelectorAll('[data-print]').forEach(b=>b.onclick=()=>printJob(b.dataset.print));document.querySelectorAll('[data-fail]').forEach(b=>b.onclick=()=>ack(b.dataset.fail,'failed','Отбелязано ръчно')); }
  function receipt(j){const p=j.payload||{},staff=destination==='staff';const rows=(p.items||[]).map(i=>`<div><b>${i.quantity} × ${Z.esc(i.name)}</b>${i.note?`<br>Бележка: ${Z.esc(i.note)}`:''}${staff&&i.unit_price!=null?`<div class="receipt-row"><span>${Number(i.quantity)} × ${Number(i.unit_price).toFixed(2)}</span><span>${(Number(i.quantity)*Number(i.unit_price)).toFixed(2)} лв.</span></div>`:''}</div><br>`).join('');return `<div class="receipt"><h1>ZORBAS</h1><h2>${title(j.job_type)}</h2><hr><div class="big">${p.order_type==='pickup'?'ПАКЕТ':`МАСА ${Z.esc(p.table_number||'—')}`}</div><div>Поръчка №${Z.esc(p.order_number||'—')}</div><div>${Z.formatDate(p.created_at||j.created_at)}</div>${p.actor?`<div>Сервитьор: ${Z.esc(p.actor)}</div>`:''}${p.ready_at?`<div>За час: ${Z.formatDate(p.ready_at)}</div>`:''}<hr>${rows}${p.cancel_reason?`<hr><b>ОТКАЗ:</b><br>${Z.esc(p.cancel_reason)}`:''}${p.note||p.order_note?`<hr><b>БЕЛЕЖКА:</b><br>${Z.esc(p.note||p.order_note)}`:''}${staff&&p.subtotal!=null?`<hr><div class="receipt-row big"><span>ОБЩО</span><span>${Number(p.subtotal).toFixed(2)} лв.</span></div>`:''}<hr><div style="text-align:center">powered by SoulFlame</div></div>`}
  async function printJob(id){const j=jobs.find(x=>x.id===id);if(!j)return;const root=$('printRoot');root.innerHTML=receipt(j);root.style.display='block';try{await ack(id,'printing');window.print();await ack(id,'printed');}catch(e){await ack(id,'failed',e.message)}finally{root.style.display='none';root.innerHTML='';await refresh();}}
  async function ack(id,status,error=null){try{return await Z.rpc('zorbas_ack_print_job_v3',{p_token:Z.token(),p_job_id:id,p_status:status,p_error:error})}catch(e){Z.toast(e.message,'error')}}
  document.addEventListener('DOMContentLoaded',()=>{Z.registerPwa();$('loginForm').onsubmit=login;$('logoutButton').onclick=Z.logout;$('refreshButton').onclick=refresh;document.querySelectorAll('[data-destination]').forEach(b=>b.onclick=()=>{destination=b.dataset.destination;document.querySelectorAll('[data-destination]').forEach(x=>x.classList.toggle('active',x===b));refresh()});start().catch(()=>{})});
})();